feat:adicionar interface  de cadastro do parceiro part1
dline-code/badaaye-front pull request #45
Opened 2022-11-24 13:08 UTC by Osvaldo943

Interface de cadastro do parceiro part1 adicionado sem a remoção do header e footer

2022-11-24 19:26 UTC, jgoncalves8080 requested changes

2022-11-24 19:26 UTC, jgoncalves8080 commented on src/views/parceiro/index.tsx
> +import { HiArrowNarrowLeft } from 'react-icons/hi'
Porquê não agrupar em um único import?

`import { HiUser,  RiLockPasswordFill, HiArrowNarrowLeft} from 'react-icons/hi'`

2022-11-24 19:26 UTC, jgoncalves8080 commented on src/views/parceiro/index.tsx
> +  const [color, setColor] = useState('blue')
Que tal colocar a tipagem dele?

  const [color, setColor] = useState<"gray" | "blue">('blue')

2022-11-24 19:26 UTC, jgoncalves8080 commented on src/views/parceiro/styles.ts
> +  background: #ffffff;
Usar as cores do `theme`

2022-11-24 19:26 UTC, jgoncalves8080 commented on src/views/parceiro/styles.ts
> +  margin-top: 1.5rem;
Acredito que tem essa medida no `theme` também

2022-11-24 19:26 UTC, jgoncalves8080 commented on src/views/parceiro/styles.ts
> +    margin-top: 2.5rem;
Usar do `theme`, caso exista

2022-11-24 19:29 UTC, jgoncalves8080 reviewed
Ver regras para título de PR: https://github.com/dline-code/badaaye-front/blob/main/CONTRIBUTING.md

2022-11-25 12:44 UTC, jgoncalves8080 requested changes
![image](https://user-images.githubusercontent.com/50240569/203988285-58c6d90d-cbbb-4980-9707-ccbe30bc23a3.png)

![image](https://user-images.githubusercontent.com/50240569/203988501-1df29aa2-bdcc-4970-93e3-642a8c22cd48.png)

O layout não está fiel ao protótipo.

2022-11-29 13:18 UTC, Osvaldo943 commented
> ![image](https://user-images.githubusercontent.com/50240569/203988285-58c6d90d-cbbb-4980-9707-ccbe30bc23a3.png)
> 
> ![image](https://user-images.githubusercontent.com/50240569/203988501-1df29aa2-bdcc-4970-93e3-642a8c22cd48.png)
> 
> O layout não está fiel ao protótipo.

Na minha máquina está assim...
![Captura de Tela (22)](https://user-images.githubusercontent.com/74511769/204539150-dfc4d5b1-ef0e-4e33-9faa-cce7118d3e89.png)

Mas vou mudar algumas estillizações...

2022-11-30 19:39 UTC, jgoncalves8080 reviewed
![image](https://user-images.githubusercontent.com/50240569/204892612-3e52822d-ea3a-47b2-bd1c-dca83c3285ff.png)

2022-11-30 20:15 UTC, Osvaldo943 commented
> ![image](https://user-images.githubusercontent.com/50240569/204892612-3e52822d-ea3a-47b2-bd1c-dca83c3285ff.png)

Problema Resolvido

2022-11-30 20:28 UTC, Osvaldo943 commented
Erros corrigidos

2022-11-30 20:55 UTC, menezescosta requested changes

2022-11-30 20:55 UTC, menezescosta commented on src/views/parceiro/styles.ts
> +  margin-top: -15px;
wy aqui está em px!

2022-11-30 20:55 UTC, menezescosta commented on src/views/parceiro/index.tsx
> +import {Layout} from "src/components/layout"
esse component não está a ser usado!

2022-11-30 20:55 UTC, menezescosta commented on src/views/parceiro/index.tsx
> +import Descontos from '../../pages/descontos/index'
esse component não está a ser usado!

2022-11-30 22:18 UTC, Osvaldo943 commented on src/views/parceiro/index.tsx
> +import {Layout} from "src/components/layout"
Este componente está sendo usado para apresentar o header e o footer.

2022-12-05 22:26 UTC, menezescosta submitted a review, later dismissed
reviewed!

2022-12-13 22:49 UTC, jgoncalves8080 requested changes
![image](https://user-images.githubusercontent.com/50240569/207461676-581ff304-0c17-41c1-8bd3-b0b816aacd96.png)

Pra selecionar a opção Estudante, basta clicar sobre a Caixa
Já na outra opção (Parceiro) deveria acontecer o mesmo
Mas pra acontecer, devo somente clicar no radio box.

2022-12-13 22:50 UTC, jgoncalves8080 approved these changes

2022-12-16 14:19 UTC, plbpassil reviewed
Agora que vejo, também se tem errado na cor do fundo. Reparem bem, por favor!
Falo do fundo da página inteira.

2022-12-22 17:09 UTC, menezescosta commented
No prototipo componente Form tem border-radius!

2022-12-22 19:02 UTC, menezescosta submitted a review, later dismissed

2022-12-22 22:14 UTC, ggenilson commented on src/components/input/index.tsx
> +    setPasswordType(passwordType === 'password' ? 'text' : 'password')
Quando precisas fazer alteração em um state com base no valor antigo, deves sempre pegar o callback value do setState.

`setPasswordType(prevPasswordType => prevPasswordType === 'password' ? 'text' : 'password')`

2022-12-22 22:23 UTC, ggenilson commented on src/components/input/index.tsx
> +        {type === 'password' && (passwordType === 'password' ? <IoEyeOff /> : <IoEye />)}
Estas condições que levam `&&`, convém sempre prevenir no final com um `|| null` ou então usar mesmo o ternário normal.

`<span onClick={showHidePassword}>
        {type === 'password' ? (passwordType === 'password' ? <IoEyeOff /> : <IoEye />) : null}
         </span>`

2022-12-22 22:25 UTC, ggenilson commented on src/components/radiobox/index.tsx
> +      activeColor={isActive ? 'blue' : 'gray'}
O projecto não tem já uma paleta de cores para usar?
Não podemos usar directamente as cores, devemos sempre pegar elas de um arquivo colors, para evitar repetições.

2022-12-22 22:26 UTC, ggenilson commented on src/views/cadastro-estudante/index.tsx
> +              activeColor="gray"
O mesmo aqui, evitar usar as cores assim!

2022-12-27 20:00 UTC, ggenilson approved these changes

2022-12-28 19:06 UTC, menezescosta approved these changes

2022-12-28 20:19 UTC, jgoncalves8080 approved these changes

2022-12-28 20:19 UTC, merged