Feature/bd 34 criar interface de cadastro de estudante parte 2
dline-code/badaaye-front pull request #49
Opened 2022-12-19 13:44 UTC by menezescosta

2022-12-20 19:34 UTC, Osvaldo943 commented on src/views/cadastro-estudante-parte2/index.tsx
> +          <div id='input'>
Não precisa adicionar a tag div como tag pai do componente Input
O componente Input já possui um className e podes trabalhar normalmente no CSS com o mesmo.

2022-12-20 19:54 UTC, Osvaldo943 commented
![Captura de Tela (32)](https://user-images.githubusercontent.com/74511769/208754704-044a75ab-da8b-4ea1-80f5-0adf719eeb18.png)

Resolver problemas de responsividade

2022-12-20 22:55 UTC, jgoncalves8080 submitted a review, later dismissed

2022-12-21 00:07 UTC, ggenilson commented on src/pages/cadastro-estudante-parte2/index.tsx
> +import CadastroEstudantePart2 from "src/views/cadastro-estudante-parte2";
Evitar utilizar Português e Inglês ao mesmo tempo na declaração de variáveis e/ou funções.

2022-12-21 00:08 UTC, ggenilson requested changes
Menezes, fiz um comentário básico, só alterar, e aprovo o PR.
O resto dá para manter, por enquanto.

2022-12-21 00:53 UTC, menezescosta commented on src/pages/cadastro-estudante-parte2/index.tsx
> +import CadastroEstudantePart2 from "src/views/cadastro-estudante-parte2";
prof eu não estou a misturar português com inglês! quando eu entrei no projecto eu já encontrei as paginas a serem exportadas ou importadas em português! eu estou a seguir!

2022-12-21 00:55 UTC, menezescosta commented on src/pages/cadastro-estudante-parte2/index.tsx
> +import CadastroEstudantePart2 from "src/views/cadastro-estudante-parte2";
ainda assim devo alterar o nome para inglês??

2022-12-21 15:25 UTC, ggenilson commented on src/pages/cadastro-estudante-parte2/index.tsx
> +import CadastroEstudantePart2 from "src/views/cadastro-estudante-parte2";
Melhor, convém melhorar os pequenos erros encontrados, para depois não ser algo grande.

2022-12-22 12:39 UTC, Osvaldo943 submitted a review, later dismissed

2022-12-22 16:37 UTC, menezescosta commented on src/pages/cadastro-estudante-parte2/index.tsx
> +import CadastroEstudantePart2 from "src/views/cadastro-estudante-parte2";
alterado prof

2022-12-22 16:44 UTC, Osvaldo943 approved these changes

2023-01-06 12:33 UTC, jgoncalves8080 commented on src/pages/cadastro-estudante-parte2/index.tsx
> +import CadastroEstudantePart2 from "src/views/cadastro-estudante-parte2";
Sempre que resolver, clicar no botão abaixo `"Resolve conversation"`

2023-01-06 12:42 UTC, jgoncalves8080 commented on src/views/cadastro-estudante-parte2/index.tsx
> +          <div id='input'>
Notificar e clicar no botão abaixo `"Resolve conversation"` assim que terminar a correção

2023-01-06 12:42 UTC, jgoncalves8080 approved these changes

2023-01-06 12:43 UTC, merged