Bugfix/bd 43 adiciona responsividade no componente contacto
dline-code/badaaye-front pull request #50
Opened 2022-12-30 19:32 UTC by menezescosta

2023-01-04 15:05 UTC, Osvaldo943 commented on src/views/studant-resistration-part2/index.tsx
> +const StudantResistrationPart2: NextPage = () => {
Usar palavras corretas em inglês

StudentRegistrationPart2

2023-01-04 15:05 UTC, Osvaldo943 commented on src/views/studant-resistration-part2/index.tsx
> +export default StudantResistrationPart2;
Mudar o nome

StudentRegistrationPart2

2023-01-04 15:05 UTC, Osvaldo943 commented on src/views/studant-resistration-part2/styles.ts
> +  background: ${({theme})=> theme.colors.tertiary.white};
Usar font do theme

2023-01-04 15:05 UTC, Osvaldo943 commented on src/views/studant-resistration-part2/styles.ts
> +  transition: 2s;
Usar transition do theme

padding: ${({theme})=> theme.transition.default};

Tens 3 opções:
default
fast
slow

2023-01-04 15:08 UTC, Osvaldo943 commented
Precisas atualizar a sua branch (fazendo pull), pude verificar que ainda não tens a branch atualizada visto que o Gonçalves aceitou uma nova PR

2023-01-04 15:09 UTC, Osvaldo943 commented on src/components/contactos/index.tsx
>              <input type="text" />
Usar componente Input

2023-01-05 13:24 UTC, menezescosta commented on src/components/contactos/index.tsx
>              <input type="text" />
aqui não vai dar para utilizar aquele componente input! porque aquele! tem bordas diferentes além disso tem uma propriedade icon!

2023-01-06 12:46 UTC, jgoncalves8080 requested changes
![image](https://user-images.githubusercontent.com/50240569/211015196-9fa6d74a-f056-491d-aa05-0ee46fb169f8.png)
Acredito que querias escrever "Seu email"

2023-01-06 12:47 UTC, jgoncalves8080 submitted a review, later dismissed

2023-01-27 14:42 UTC, plbpassil commented
Tem atualizações a fazer aqui. Vamos trabalhar até a perfeição.

2023-02-09 06:14 UTC, Osvaldo943 approved these changes

2023-02-09 20:01 UTC, jgoncalves8080 approved these changes

2023-02-10 10:27 UTC, merged