Bd 67 cadastro de estudante parte 1 consumo
dline-code/badaaye-front pull request #57
Opened 2023-02-22 10:22 UTC by Antoniopedromuteka

2023-02-22 18:45 UTC, plbpassil reviewed
@Antoniopedromuteka essa PR tem conflito!

2023-02-23 11:02 UTC, Osvaldo943 commented
Esta PR falhou no teste e não poderá ser mesclada.
Verificar o erro usando o camando:
yarn build

2023-02-23 15:04 UTC, mauriciocosta404 commented
pr tem conflitos!

2023-02-23 18:51 UTC, EduardoPanzo requested changes
veja se há comflitos

2023-02-27 21:01 UTC, EduardoPanzo approved these changes

2023-02-28 20:02 UTC, mauriciocosta404 approved these changes

2023-02-28 20:21 UTC, merged