Bd 79 criar tela de solicitacao de financiamento
dline-code/badaaye-front pull request #60
Opened 2023-03-02 01:27 UTC by Antoniopedromuteka

ainda não terminei a task

2023-03-02 10:44 UTC, Osvaldo943 requested changes

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +        padding-left: 5rem;
Usar o theme: 
padding-left: ${({theme})=> theme.spacings.xmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +        padding-left: 5rem;
Usar os spacings do theme:
padding-left: ${({theme})=> theme.spacings.xmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +        padding-right: 5rem;
Usar os spacings theme:
padding-left: ${({theme})=> theme.spacings.xmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +        padding-left: 2rem;
Usar os spacings theme:
padding-left: ${({theme})=> theme.spacings.xxxmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +        padding-right: 2rem;
Usar os spacings theme:
padding-left: ${({theme})=> theme.spacings.xxxmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +    padding: 0rem 5rem;
Usar os spacings theme:
padding: 0  ${({theme})=> theme.spacings.xmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +    gap: 1rem;
Usar os spacings theme:
gap: ${({theme})=> theme.spacings.xxxxmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +    gap: 2rem;
Usar os spacings theme:
gap: ${({theme})=> theme.spacings.xxxmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +    padding: 0 2rem;
Usar os spacings theme:
padding: 0  ${({theme})=> theme.spacings.xxxmultipleeight};

2023-03-02 10:44 UTC, Osvaldo943 commented on src/views/solicitacao-de-financiamento/styles.ts
> +    padding: 0 5rem;
Usar os spacings theme:
padding: 0  ${({theme})=> theme.spacings.xmultipleeight};

2023-03-02 10:45 UTC, plbpassil reviewed
As bordas das inputs não estão conforme.
Precisas centralizar o formulário.
Não esqueça: a input do vídeo motivacional tem estilização diferente.

2023-03-02 11:14 UTC, Osvaldo943 commented
Há necessidade de trabalhar sempre com as propriedades que se encontram no theme.

2023-03-02 12:28 UTC, Osvaldo943 commented
![Captura de ecrã_2023-03-02_11-29-41](https://user-images.githubusercontent.com/74511769/222428535-54a56161-543a-4550-8182-35889166c6a7.png)
Este layout não está comforme o protótipo

![Captura de ecrã_2023-03-02_11-30-05](https://user-images.githubusercontent.com/74511769/222428787-8af6a3df-7ec7-499f-8010-d4421b9b154e.png)
Aqui temos o protótipo

2023-03-02 12:29 UTC, Osvaldo943 commented
![Captura de ecrã_2023-03-02_11-30-55](https://user-images.githubusercontent.com/74511769/222428973-89feaa3a-06e9-4a1f-8f42-e10211ad1106.png)
Não está comforme o protótipo

![Captura de ecrã_2023-03-02_11-31-12](https://user-images.githubusercontent.com/74511769/222429149-8e99d5d3-3b92-4042-99d2-a8ad8f2d41fe.png)
Aqui temos o protótipop

2023-03-06 12:22 UTC, plbpassil reviewed
Precisas ver essas questões e terminar o consumo.
Ainda temos mais trabalho pela frente.
Deves resolver as conversas que já reviste.

2023-03-06 12:22 UTC, plbpassil commented on src/views/solicitacao-de-financiamento/index.tsx
> +                            <S.ContainerInput>
A borda das Inputs não estão fiéis ao layout. Parece apenas uma linha preta, magra e feia. Não parece uma borda tranparente.

2023-03-06 12:22 UTC, plbpassil commented on src/views/solicitacao-de-financiamento/index.tsx
> +                                <S.Select>
Pode remover o sexo.

2023-03-06 12:22 UTC, plbpassil commented on src/views/solicitacao-de-financiamento/index.tsx
> +                                <S.Label>Estado cívil</S.Label>
Pode remover também o estado civil.

2023-03-22 22:49 UTC, mauriciocosta404 commented
resolver conflito!

2023-03-22 23:02 UTC, Antoniopedromuteka commented
> resolver conflito!

ainda não terminei a task, estou esperando o back-end

2023-03-28 22:46 UTC, Osvaldo943 commented
Resolver falhas no teste.

2023-09-20 07:16 UTC, closed without merging