Feature/Bd-77-criar-tela-de-dados-completos-do-estudante
dline-code/badaaye-front pull request #61
Opened 2023-03-02 05:45 UTC by EduardoPanzo

2023-03-02 10:19 UTC, plbpassil commented on src/views/dados-estudante/index.tsx
> +              />
Faltam muitas inputs.

2023-03-02 10:35 UTC, plbpassil reviewed
A font e o tamanho das letras não parece ser o mesmo.
Falta muito para terminar essa página.

2023-03-06 12:15 UTC, plbpassil reviewed
Precisamos falar sobre a validação desses dados e como deve funcionar essa questão.

2023-03-06 12:15 UTC, plbpassil commented on src/views/dados-estudante/hooks/useStudentData.ts
> +        .min(5, 'O campo deve ter no mínimo 5 caracteres')
Qual é essa dos 5 caracteres apenas. Revê!

2023-03-06 19:25 UTC, EduardoPanzo commented on src/views/dados-estudante/hooks/useStudentData.ts
> +      senha: Yup.string()
Essas são as regra de cada campo

2023-03-06 19:26 UTC, EduardoPanzo commented on src/views/dados-estudante/hooks/useStudentData.ts
> +        .min(5, 'O campo deve ter no mínimo 5 caracteres')
Não é 5 apenas, mas sim no mínimo, não temos uma regra estabelecida para esses campos então, os define assim

2023-03-08 16:53 UTC, EduardoPanzo commented
> ess page precisa de um usuárioId

não precisa

2023-03-09 17:53 UTC, Osvaldo943 commented
Click em resolve para todos os reviews feito, caso eles já foram corrigidos

2023-03-15 00:18 UTC, jgoncalves8080 requested changes

2023-03-15 00:18 UTC, jgoncalves8080 commented on src/views/dados-estudante/hooks/useStudentData.ts
> +  let optionsSelects: any = {
Que tal colocar a tipagem certa ao invés de `any`?

2023-03-15 00:18 UTC, jgoncalves8080 commented on src/views/dados-estudante/hooks/useStudentData.ts
> +  const { data, isFetching } = useQuery(
O `useQuery` retorna também uma propriedade `error`, pra monitorar caso tenha dado algum erro na requisição.

2023-03-15 00:18 UTC, jgoncalves8080 commented on src/views/dados-estudante/hooks/useStudentData.ts
> +    validationShema: Yup.object({
Que tal inserir a validação em outro ficheiro?

2023-03-15 00:18 UTC, jgoncalves8080 commented on src/views/dados-estudante/styles.ts
> +    #fff 240px
Existe um theme pra essa cor

2023-03-15 00:18 UTC, jgoncalves8080 commented on src/views/dados-estudante/styles.ts
> +  max-width: 540px;
` max-width: 54rem;
`

2023-03-15 08:55 UTC, EduardoPanzo commented on src/views/dados-estudante/hooks/useStudentData.ts
> +  const { data, isFetching } = useQuery(
faço já agora mesmo

2023-03-15 08:56 UTC, EduardoPanzo commented on src/views/dados-estudante/hooks/useStudentData.ts
> +    validationShema: Yup.object({
ok

2023-03-15 19:24 UTC, Osvaldo943 commented
O nome branch está incompleto, nomear:
feature/BD-77-Criar-tela-de-dados-completos-do-estudante

2023-03-15 19:37 UTC, Osvaldo943 approved these changes

2023-03-16 11:42 UTC, plbpassil reviewed
![Captura de Ecrã (131)](https://user-images.githubusercontent.com/74856948/225606243-50210c11-f9e0-4362-984b-b2e9a7b97889.png)

Estou tentando alterar apenas a província, e ele me obriga a alterar, para além do município e bairro que até aqui está certo, o curso e o grau. Devia?

2023-03-16 11:54 UTC, plbpassil reviewed
Coloque um alerta ao lado dos dados que estiverem vazios. Esse alerta laranja, deve aconselhá-lo a preencher esses dados. Isso, sem precisar ser na tentativa de alterar algum dado. Não precisas remover a obrigação ao tentar alterar.

2023-03-17 06:01 UTC, EduardoPanzo commented
> ![Captura de Ecrã (131)](https://user-images.githubusercontent.com/74856948/225606243-50210c11-f9e0-4362-984b-b2e9a7b97889.png)
> 
> Estou tentando alterar apenas a província, e ele me obriga a alterar, para além do município e bairro que até aqui está certo, o curso e o grau. Devia?

# Estas a dizer que os campos não devem ser óbrigatório?!

2023-03-20 12:30 UTC, mauriciocosta404 commented
ele é obrigado a alterar todos os dados??

2023-03-21 11:45 UTC, mauriciocosta404 submitted a review, later dismissed

2023-03-21 18:05 UTC, plbpassil reviewed
![Captura de Ecrã (247)](https://user-images.githubusercontent.com/74856948/226701328-ec45316e-1e73-4be7-ae93-3c4ab2fb92d9.png)
Quando tento atualizar, nos dados vazios pede todos, excepto a universidade!
Porquê?

2023-03-21 19:23 UTC, EduardoPanzo commented on src/views/dados-estudante/styles.ts
> +  padding: 2.5rem 2rem 1rem;
O theme precisa de ajuste

2023-03-22 13:36 UTC, Antoniopedromuteka commented on src/views/dados-estudante/service/index.ts
> +    // dataNascimento:data.da,
porquê comentaste?

2023-03-22 13:36 UTC, Antoniopedromuteka commented on src/views/dados-estudante/type.ts
> +  // loginId:string
aqui também!

2023-03-22 16:33 UTC, plbpassil approved these changes

2023-03-27 09:11 UTC, merged