Feature/BD-consumo-cadastro-estudante-parte2
dline-code/badaaye-front pull request #64
Opened 2023-03-02 15:01 UTC by mauriciocosta404

2023-03-02 15:51 UTC, Osvaldo943 requested changes

2023-03-02 15:51 UTC, Osvaldo943 commented on src/views/cadastro-estudante-parte2/hooks/useValidateData.ts
> +    async function StudentregistrationPart2(data: IStudent){
Usar camel case na nomeação das funções
StudentRegistrationPart2()

2023-03-02 23:32 UTC, Antoniopedromuteka commented on src/views/cadastro-estudante-parte2/hooks/useValidateData.ts
> +            const student = await putFetchStudentPart2(data)
porque essa funcão tem o nome de put??

2023-03-02 23:32 UTC, Antoniopedromuteka commented on src/views/cadastro-estudante-parte2/hooks/useFetschStudent.ts
> +  const [provinces, setProvinces] = useState([])
não é nada performático usares muitos useStates

2023-03-02 23:32 UTC, Antoniopedromuteka commented on src/views/cadastro-estudante-parte2/hooks/useFetschStudent.ts
> +  const getDataProvince= async () => {
tenta refatorar a maneira de como você pegas os dados da api

2023-03-02 23:32 UTC, Antoniopedromuteka commented on src/views/cadastro-estudante-parte2/hooks/useFetschStudent.ts
> +  useEffect(() => {
porquê não usas um react query ou swr?

2023-03-02 23:32 UTC, Antoniopedromuteka commented on src/views/cadastro-estudante-parte2/index.tsx
> +  useEffect(()=>{
não percebi este trecho de código

2023-03-02 23:32 UTC, Antoniopedromuteka commented on src/views/cadastro-estudante-parte2/index.tsx
> +  useEffect(()=>{
cuidado com o uso do useEffect

2023-03-03 03:48 UTC, EduardoPanzo requested changes

2023-03-03 03:48 UTC, EduardoPanzo commented on src/views/cadastro-estudante-parte2/index.tsx
> +  },[formik.values.provinciaId])
Recomendo vc usar uma ferramenta de fetching como react-query ou swr e parar de usar useEffect

2023-03-03 22:29 UTC, mauriciocosta404 commented on src/views/cadastro-estudante-parte2/hooks/useValidateData.ts
> +            const student = await putFetchStudentPart2(data)
porque a parte 2 é um método put!

2023-03-06 12:28 UTC, plbpassil commented on src/views/cadastro-estudante-parte2/hooks/useValidateData.ts
> +            studentRegistrationPart2(data);
Você é o responsável por linkar a página do cadastro parte1 com a parte 2.
Garantir que ninguém venha para essa página sem ter saído da primeira.
Garantir que quem venha para essa página, venha sempre com, no mínimo, o campo estudanteId.

2023-03-07 18:10 UTC, Osvaldo943 submitted a review, later dismissed

2023-03-07 20:04 UTC, EduardoPanzo submitted a review, later dismissed

2023-03-07 20:18 UTC, plbpassil reviewed
Tem conflitos!

2023-03-08 16:40 UTC, plbpassil approved these changes
Tal como devia! Parabéns!

2023-03-08 17:02 UTC, merged