feat: private protected pages
dline-code/badaaye-front pull request #66
Opened 2023-03-29 06:32 UTC by Osvaldo943

2023-03-29 15:54 UTC, EduardoPanzo requested changes
Ao entrar numa pagina protegida, ela está a entrar e por um instante nos leva a pagina de login, ou seja:  A proteção está a atrasar

2023-03-29 15:54 UTC, EduardoPanzo commented on src/views/dados-estudante/index.tsx
> +    //authContext.isUserAuthenticated()
comentário

2023-03-31 15:02 UTC, plbpassil reviewed
Se ele já estiver logado, não pode mais ficar na landpage!
Se puder ficar, deve haver algo mostrando pra ele que está logado!

2023-03-31 15:07 UTC, plbpassil reviewed
Continua com o mesmo problema reportado pelo Panzo.

2023-04-04 11:04 UTC, plbpassil reviewed
Tem conflitos!

2023-04-06 20:03 UTC, EduardoPanzo requested changes
@Osvaldo943, acho deves mudar a tua lógica de privatização de pagina, eu não tenho uma para te sugerir, mas o que estás a usar não está a fazer o desfio imedito, ou seja, está a entrar na pagina desejada e só assim está a ir na pagina de login....

2023-04-09 11:01 UTC, Osvaldo943 commented on src/pages/tela-principal-estudante/_middleware.ts
> +    if (!verifyToken && url === "http://localhost:3000") {
Aqui na minha máquina ela redireciona imediatamente porque middleware são executadas antes mesmo que a parte do client-side é executada mas vou procurar por uma melhor forma de fazer isso, obrigado.

2023-04-10 09:56 UTC, plbpassil reviewed
Essa tarefa, é bem mais complexa do que parece!

Eis o que espero dela:
* Se o usuário estiver logado, não deve ser possível acessar a página de login;
* Se o usuário estiver logado, não deve ser possível acessar a landpage;
* O estudante não pode conseguir acessar a rota do parceiro, nem o parceiro do estudante - com rigor;
Faça tudo isso. Valide tudo! Faça o mais breve possível.

2023-05-11 22:48 UTC, Antoniopedromuteka commented
> 

realmente mano.

2023-05-16 18:57 UTC, Osvaldo943 commented
> @Osvaldo943, acho deves mudar a tua lógica de privatização de pagina, eu não tenho uma para te sugerir, mas o que estás a usar não está a fazer o desfio imedito, ou seja, está a entrar na pagina desejada e só assim está a ir na pagina de login....

@EduardoPanzo já há uma nova lógica disponível podes checar...

2023-05-17 10:50 UTC, plbpassil approved these changes

2023-05-17 18:27 UTC, EduardoPanzo approved these changes

2023-05-17 19:28 UTC, merged